version: 2.1

orbs:
  node: cimg/node:17.9.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm i

workflows:
  version: 2.1
  build:
    jobs:
      - build
