
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: ls -l
      - run: npm i
      - run: npm run dev

workflows:
  version: 2.1
  build:
    jobs:
      - build
