version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test:cov
          

workflows:
  version: 2.1
  build:
    jobs:
      - build